apiVersion: v1
kind: Pod
metadata:
  name: javaapp
  labels:
    app: javaapp
spec:
  containers:
    - name: nodeapp
      image: abhilashnarayan/javaapp:tagVersion
      ports:
        - containerPort: 8081
